before:
  hooks:
    - go mod tidy
builds:
  - id: declutter
    main: ./cmd/declutter
    binary: declutter
    ldflags:
      - -s -w
      - -X github.com/eddie023/declutter/internal/build.Version={{.Version}}
      - -X github.com/eddie023/declutter/internal/build.Commit={{.Commit}}
      - -X github.com/eddie023/declutter/internal/build.Date={{.Date}}
      - -X github.com/eddie023/declutter/internal/build.BuiltBy=eddie023releaser
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
